# Generated by Django 5.2.13 on 2026-04-24 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encomienda',
            options={'verbose_name': 'Encomienda', 'verbose_name_plural': 'Encomiendas'},
        ),
        migrations.AddField(
            model_name='encomienda',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encomienda',
            name='peso',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='encomienda',
            table='encomiendas',
        ),
    ]
