# Generated by Django 5.2.13 on 2026-04-24 00:43

import django.core.validators
import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_alter_encomienda_options_encomienda_fecha_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomienda',
            name='codigo',
            field=models.CharField(default='ENC-000', max_length=20, unique=True, validators=[envios.validators.validar_codigo_encomienda]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='peso',
            field=models.FloatField(validators=[envios.validators.validar_peso_positivo, django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
