# Generated by Django 5.2.13 on 2026-04-24 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('envios', '0003_encomienda_codigo_alter_encomienda_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomienda',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios_recibidos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_realizados', to='clientes.cliente'),
        ),
    ]
