# Generated by Django 5.2.13 on 2026-04-24 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_encomienda_destinatario_encomienda_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.encomienda')),
            ],
            options={
                'db_table': 'historial_estados',
            },
        ),
    ]
