# Generated by Django 6.0.4 on 2026-05-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0005_historialestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomienda',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En tránsito'), ('entregada', 'Entregada'), ('retrasada', 'Retrasada')], default='pendiente', max_length=20),
        ),
    ]
