# Generated by Django 5.2.13 on 2026-04-24 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AddField(
            model_name='ruta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruta',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='ruta',
            table='rutas',
        ),
    ]
